// Client-side verification: BMT chunk addressing, a verifying chunk
// store over GET /chunks, a verified tree reader, and single-owner
// chunk (feed update) verification. Line-for-line ports of swarmfs's
// bmt.py / join.py / feeds.py — the two implementations are held
// together by shared fixtures (js/test/fixtures/, generated BY swarmfs).
//
// This is what makes reads through an UNTRUSTED endpoint (a public
// gateway) actually trustless: a Swarm reference is the hash of the
// content, so a tampering gateway is caught on the first bad chunk.
// Against a local light node the node verifies natively and the plain
// Range-read path is faster — see open()'s `verify` option.

import { keccak256Bytes } from '../vendor/js-sha3/index.js';
import { Signature } from '../vendor/noble-secp256k1/index.js';

export const CHUNK_SIZE = 4096;
const SEGMENT = 32;
const REF_SIZE = 32;
const SOC_IDENTIFIER_SIZE = 32;
const SOC_SIGNATURE_SIZE = 65;
const SOC_SPAN_OFFSET = SOC_IDENTIFIER_SIZE + SOC_SIGNATURE_SIZE; // 97
const FETCH_TIMEOUT_MS = 30_000;

export class VerificationError extends Error {
  name = 'VerificationError';
}

export const toHex = (bytes) =>
  Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');

export function fromHex(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(2 * i, 2 * i + 2), 16);
  }
  return out;
}

function concat(...parts) {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let off = 0;
  for (const p of parts) { out.set(p, off); off += p.length; }
  return out;
}

// ---- BMT addressing -------------------------------------------------------

/** Root of the binary Merkle tree over 32-byte segments of the payload,
 * zero-padded to 4096 bytes. */
export function bmtRoot(payload) {
  if (payload.length > CHUNK_SIZE) {
    throw new VerificationError(`payload size ${payload.length} exceeds ${CHUNK_SIZE}`);
  }
  const padded = new Uint8Array(CHUNK_SIZE);
  padded.set(payload);
  let level = [];
  for (let i = 0; i < CHUNK_SIZE; i += SEGMENT) {
    level.push(padded.subarray(i, i + SEGMENT));
  }
  while (level.length > 1) {
    const next = [];
    for (let i = 0; i < level.length; i += 2) {
      next.push(keccak256Bytes(concat(level[i], level[i + 1])));
    }
    level = next;
  }
  return level[0];
}

/** BMT address of a content-addressed chunk (data = span + payload). */
export function chunkAddress(data) {
  return keccak256Bytes(concat(data.subarray(0, 8), bmtRoot(data.subarray(8))));
}

/** Little-endian span -> content length. Bee stores the erasure-coding
 * redundancy level in the top byte (span[7] > 128). */
export function decodeSpan(span) {
  let size = 0;
  for (let i = 6; i >= 0; i--) size = size * 256 + span[i];
  if (span[7] <= 128) size += span[7] * 256 ** 7;
  return size;
}

// ---- verifying chunk store ------------------------------------------------

/** Fetches raw chunks via GET /chunks/{ref} and verifies each against
 * the reference it was requested by. Content-addressed, so the cache
 * never goes stale. */
export class VerifiedChunkStore {
  #cache = new Map(); // ref hex -> Uint8Array (Map keeps LRU order)
  #cacheChunks;
  #fetch;
  apiUrl;
  stats = { chunksFetched: 0, bytesFetched: 0 };

  constructor(apiUrl, { cacheChunks = 4096, fetchFn } = {}) {
    this.apiUrl = apiUrl.replace(/\/+$/, '');
    this.#cacheChunks = Math.max(1, cacheChunks);
    this.#fetch = fetchFn ?? ((...args) => globalThis.fetch(...args));
  }

  /** One verified chunk (span + payload) by 64-hex reference. */
  async chunk(refHex) {
    const hit = this.#cache.get(refHex);
    if (hit !== undefined) {
      this.#cache.delete(refHex); // refresh LRU position
      this.#cache.set(refHex, hit);
      return hit;
    }
    const resp = await this.#fetch(`${this.apiUrl}/chunks/${refHex}`, {
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    });
    if (!resp.ok) {
      throw new Error(`HTTP ${resp.status} fetching chunk ${refHex.slice(0, 16)}…`);
    }
    const data = new Uint8Array(await resp.arrayBuffer());
    if (toHex(chunkAddress(data)) !== refHex) {
      throw new VerificationError(
        `chunk ${refHex.slice(0, 16)}… failed verification: content does ` +
        'not hash to its address (tampering, corruption, or a bad endpoint)',
      );
    }
    this.stats.chunksFetched += 1;
    this.stats.bytesFetched += data.length;
    this.#cache.set(refHex, data);
    while (this.#cache.size > this.#cacheChunks) {
      this.#cache.delete(this.#cache.keys().next().value);
    }
    return data;
  }
}

// ---- verified tree reader -------------------------------------------------

function rootRef(refHex) {
  if (refHex.length !== 64) {
    throw new VerificationError(
      `cannot verify reference ${refHex.slice(0, 16)}…: encrypted ` +
      '(128-hex) references are not supported by the verifying reader yet',
    );
  }
  return refHex;
}

/** Verified content length of a reference. */
export async function verifiedSize(store, refHex) {
  return decodeSpan((await store.chunk(rootRef(refHex))).subarray(0, 8));
}

/** Verified read of [start, end) of a reference's content, descending
 * only the subtrees the range needs. */
export async function verifiedRead(store, refHex, start, end) {
  const chunk = await store.chunk(rootRef(refHex));
  const size = decodeSpan(chunk.subarray(0, 8));
  const s = Math.min(start ?? 0, size);
  const e = end === undefined ? size : Math.min(end, size);
  if (e <= s) return new Uint8Array(0);
  const out = new Uint8Array(e - s);
  await readTree(store, chunk, s, e, out, 0);
  return out;
}

/** Append [start, end) of this subtree (both subtree-relative) into
 * out at outPos; returns bytes written. An intermediate chunk's payload
 * holds the data child references first (exactly ceil(span/unit)), then
 * parity references when erasure coding is on — those are ignored.
 *
 * The per-child span `unit` is read from the FIRST child's own span
 * rather than computed as a power of 128: with erasure coding the
 * effective fanout is smaller (seen live: 107 data + 21 parity refs per
 * intermediate on a redundancy-uploaded file), and every child but the
 * last spans the same unit — a Bee tree invariant this walk verifies. */
async function readTree(store, chunk, start, end, out, outPos) {
  const size = decodeSpan(chunk.subarray(0, 8));
  const payload = chunk.subarray(8);
  if (size <= CHUNK_SIZE) {
    const piece = payload.subarray(start, end);
    out.set(piece, outPos);
    return piece.length;
  }
  if (payload.length < REF_SIZE) {
    throw new VerificationError('intermediate chunk has no child references');
  }
  const first = await store.chunk(toHex(payload.subarray(0, REF_SIZE)));
  const unit = decodeSpan(first.subarray(0, 8));
  if (unit <= 0 || unit >= size) {
    throw new VerificationError(
      `first child spans ${unit} of a ${size}-byte subtree — not a valid tree`,
    );
  }
  const nData = Math.ceil(size / unit);
  if (payload.length < nData * REF_SIZE) {
    throw new VerificationError(
      `intermediate chunk carries ${Math.floor(payload.length / REF_SIZE)} ` +
      `references but its span requires ${nData}`,
    );
  }
  let written = 0;
  for (let i = Math.floor(start / unit); i < nData; i++) {
    const lo = i * unit;
    if (lo >= end) break;
    const hi = Math.min(lo + unit, size);
    const child = i === 0
      ? first
      : await store.chunk(toHex(payload.subarray(i * REF_SIZE, (i + 1) * REF_SIZE)));
    const childSpan = decodeSpan(child.subarray(0, 8));
    if (childSpan !== hi - lo) {
      throw new VerificationError(
        `child chunk span ${childSpan} does not match its position in ` +
        `the tree (expected ${hi - lo})`,
      );
    }
    written += await readTree(
      store, child, Math.max(start, lo) - lo, Math.min(end, hi) - lo,
      out, outPos + written,
    );
  }
  return written;
}

// ---- single-owner chunks (feed updates) -----------------------------------

/** 32-byte feed identifier: keccak256(topic ‖ index as 8-byte BE). */
export function feedIdentifier(topicBytes, index) {
  const idx = new Uint8Array(8);
  new DataView(idx.buffer).setBigUint64(0, BigInt(index), false);
  return keccak256Bytes(concat(topicBytes, idx));
}

/** Address a single-owner chunk lives at: keccak256(identifier ‖ owner). */
export function socAddress(identifier, ownerBytes) {
  return keccak256Bytes(concat(identifier, ownerBytes));
}

/** Full client-side check of a single-owner chunk: address derivation,
 * and recovery of the owner from the signature over the wrapped chunk's
 * BMT address — exactly what a Bee node checks on upload. Returns the
 * wrapped chunk's payload (the feed update). */
export function verifySoc(data, ownerBytes, addressBytes) {
  if (data.length < SOC_SPAN_OFFSET + 8) {
    throw new VerificationError(`single-owner chunk too short: ${data.length} bytes`);
  }
  const identifier = data.subarray(0, SOC_IDENTIFIER_SIZE);
  const sig = data.subarray(SOC_IDENTIFIER_SIZE, SOC_SPAN_OFFSET);
  const cac = data.subarray(SOC_SPAN_OFFSET);
  if (toHex(socAddress(identifier, ownerBytes)) !== toHex(addressBytes)) {
    throw new VerificationError('single-owner chunk does not match its address');
  }
  const digest = keccak256Bytes(concat(identifier, chunkAddress(cac)));
  const prefixed = keccak256Bytes(concat(
    new TextEncoder().encode('\x19Ethereum Signed Message:\n32'), digest,
  ));
  let recovered;
  try {
    recovered = Signature.fromCompact(sig.subarray(0, 64))
      .addRecoveryBit(sig[64] - 27)
      .recoverPublicKey(prefixed)
      .toBytes(false); // uncompressed: 0x04 ‖ x ‖ y
  } catch (e) {
    throw new VerificationError(`feed update signature is malformed: ${e}`);
  }
  const recoveredOwner = keccak256Bytes(recovered.subarray(1)).subarray(12);
  if (toHex(recoveredOwner) !== toHex(ownerBytes)) {
    throw new VerificationError('feed update signature was not made by the feed owner');
  }
  return cac.subarray(8); // the update payload (timestamp + reference)
}
